version: "3.9"

services:
  prod-api-mitm-institute:
    container_name: prod-api-mitm-institute
    build:
      context: .
      dockerfile: ./apps/api-mitm-institute/Dockerfile
    ports:
      - 3001:3001
    command: yarn turbo start
